services:
  db:
    image: mysql:8.0
    container_name: cr_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: complaints
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: cr_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env   # loads DB_URL, DB_USER, DB_PASSWORD
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: cr_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
